import type { Metadata } from 'next'
import './globals.css'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import { Inter } from 'next/font/google'
import '@mantine/core/styles.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'lanndi',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <ColorSchemeScript />
        </head>
        <body className={inter.className}>
        <MantineProvider>{children}</MantineProvider>
        </body>
        </html>
    )

}
